spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StudentDev10/microservice-assignment-config
          clone-on-start: true
        
server:
  port: 8084
  

